apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
