apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-app
  title: Create a new Go app
  description: |
    A template for creating a new Go app with following features:
    - GitHub Repo
    - Tekton CI/CD
    - KubeVela Application
    - ArgoCD Application
spec:
  owner: infrastructure
  type: service

  parameters:
  - title: Provide project information
    required:
    - name
    - owner
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component.
        pattern: "^[a-z0-9-]*$"
      description:
        title: Description
        type: string
        ui:widget: textarea
        ui:options:
          rows: 10
        description: Tell us more about this component!
      owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          allowedKinds:
          - Group
  - title: Create a new GitHub repository
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com
  steps:
  - id: fetch-argo
    name: Render ArgoCD Application
    action: fetch:template
    input:
      url: ./template-argo
      values:
        name: ${{parameters.name}}
        repoUrl: "https://github.com/${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}/${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}"
        description: ${{parameters.description}}
        owner: ${{parameters.owner}}

  - id: create-argo-pr
    name: Create PR to ArgoCD App of Apps repo
    action: publish:github:pull-request
    input:
      repoUrl: github.com?repo=kubecon-2023-argocd&owner=my-silly-organisation
      title: "Create new project: ${{parameters.name}}"
      branchName: create-${{parameters.name}}
      description: |
        # New KubeCon China 2023 Application ${{parameters.name}}
        
        delivered by ArgoCD App of Apps
        created by Backstage Scaffolder
      targetPath: .

  - id: remove-app-of-apps-template
    name: Delete ArgoCD App of Apps template
    action: fs:delete
    input:
      files:
      - ${{parameters.name}}-application.yaml

  - id: fetch-go-app
    name: Render Go App
    action: fetch:template
    input:
      url: ./template-app
      values:
        name: ${{parameters.name}}
        description: ${{ parameters.description }}
        repoUrl: "https://github.com/${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}/${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}"
        image: ${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}
        owner: ${{parameters.owner}}

  - id: publish
    name: Publish Go App to GitHub
    action: publish:github
    input:
      allowedHosts: ["github.com"]
      repoVisibility: public
      description: "This is ${{parameters.name}} Go App"
      repoUrl: ${{ parameters.repoUrl }}
      defaultBranch: main
      requiredApprovingReviewCount: 0
      protectDefaultBranch: false

  output:
    links:
    - url: ${{ steps['create-argo-pr'].output.remoteUrl }}
      title: "Go to PR"
    - title: Open the Source Code Repository
      url: ${{ steps['publish'].output.repoContentsUrl }}
