apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vela-template.yaml

configurations:
- kubevela-image-transformer.yaml

images:
  - name: goapp
    newName: goapp
    newTag: v1
