apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${{values.name}}-deploy-only-pipeline-run
  namespace: kubecon-china-build
spec:
  taskRunSpecs:
  - pipelineTaskName: kubevela
    taskServiceAccountName: sa-for-kubevela
  pipelineRef:
    name: ${{values.name}}-deploy-only-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
