apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all-pipeline.yaml
- all-pipeline-run.yaml
- deploy-only-pipeline.yaml
- deploy-only-pipeline-run.yaml
- kubevela-task.yaml
