apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name:  ${{values.name}}-kubevela-task
  namespace: kubecon-china-build
spec:
  params:
  - name: image-digest
    type: string
    default: latest
    description: image digest
  description: >-
    This Task builds a simple Dockerfile with kaniko and pushes to a registry.
    This Task stores the image name and digest as results, allowing Tekton Chains to pick up
    that an image was built & sign it.
  workspaces:
  - name: source
    description: Holds the code
  steps:
  - name: run-kubevela
    workingDir: $(workspaces.source.path)
    image: oamdev/vela-cli:v1.9.6
    script: |
      ls -la
      apk add curl
      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash   
      mv kustomize /usr/local/bin/
      cd .kubevela
      kustomize edit set image goapp=ghcr.io/${{values.image}}/${{values.name}}@$(params.image-digest) 
      cat kustomization.yaml
      kustomize build . | vela up -f -
      rm vela.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{values.name}}-tekton-pipeline
  namespace: kubecon-china-build
spec:
  workspaces:
  - name: shared-workspace
  - name: dockerconfig
  - name: basic-auth
  tasks:
  - name: clone-repo
    taskRef:
      kind: Task
      params:
      - name: bundle
        value: 'gcr.io/tekton-releases/catalog/upstream/git-clone:0.9'
      - name: name
        value: git-clone
      - name: kind
        value: Task
      resolver: bundles
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: ${{values.repoUrl}}
    - name: deleteExisting
      value: "true"
  - name: kaniko
    taskRef:
      kind: Task
      params:
      - name: bundle
        value: 'gcr.io/tekton-releases/catalog/upstream/kaniko:0.6'
      - name: name
        value: kaniko
      - name: kind
        value: Task
      resolver: bundles
    params:
    - name: DOCKERFILE
      value: Dockerfile
    - name: IMAGE
      value: ghcr.io/${{values.image}}/${{values.name}}
    - name: CONTEXT
      value: .
    - name: EXTRA_ARGS
      value:
      - --label=org.opencontainers.image.source=${{values.repoUrl}}
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: dockerconfig
    runAfter:
    - clone-repo
  - name: kubevela
    taskRef:
      kind: Task
      name: ${{values.name}}-kubevela-task
    params:
    - name: image-digest
      value: "$(tasks.kaniko.results.IMAGE_DIGEST)"
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: git-push
    runAfter:
    - kubevela
    taskRef:
      kind: Task
      params:
      - name: bundle
        value: 'gcr.io/tekton-releases/catalog/upstream/git-cli:0.4'
      - name: name
        value: git-cli
      - name: kind
        value: Task
      resolver: bundles
    params:
    - name: GIT_USER_EMAIL
      value: "tekton@github.com"
    - name: GIT_USER_NAME
      value: "Tekton"
    - name: GIT_SCRIPT
      value: |
        ls -la
        git config --global --add safe.directory $(workspaces.source.path)
        git add .
        git commit -am "change image tag"
        git push -u origin HEAD:refs/heads/main --force
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: basic-auth
      workspace: basic-auth
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${{values.name}}-pipeline-run
  namespace: kubecon-china-build
spec:
  taskRunSpecs:
  - pipelineTaskName: kubevela
    taskServiceAccountName: sa-for-kubevela
  pipelineRef:
    name: ${{values.name}}-tekton-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: basic-auth
    secret:
      secretName: basic-auth
      items:
      - key: .gitconfig
        path: .gitconfig
      - key: .git-credentials
        path: .git-credentials
  - name: dockerconfig
    secret:
      secretName: ghcr-auth
      items:
      - key: config.json
        path: config.json
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
